"""current schema baseline

Revision ID: 20260710_01
Revises:
Create Date: 2026-07-10 11:18:45.251059
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260710_01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_table('customer_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('xianyu_nickname', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('first_trade_at', sa.DateTime(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_blacklist', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_deleted_at'), 'customers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_customers_is_blacklist'), 'customers', ['is_blacklist'], unique=False)
    op.create_index(op.f('ix_customers_level'), 'customers', ['level'], unique=False)
    op.create_index(op.f('ix_customers_total_spent'), 'customers', ['total_spent'], unique=False)
    op.create_index(op.f('ix_customers_xianyu_nickname'), 'customers', ['xianyu_nickname'], unique=False)
    op.create_table('mail_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('email_account', sa.String(length=255), nullable=False),
    sa.Column('gpt_password', sa.String(length=512), nullable=False),
    sa.Column('token_url', sa.String(length=512), nullable=False),
    sa.Column('email_password', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_records_sent_at'), 'mail_records', ['sent_at'], unique=False)
    op.create_index(op.f('ix_mail_records_status'), 'mail_records', ['status'], unique=False)
    op.create_index(op.f('ix_mail_records_to'), 'mail_records', ['to'], unique=False)
    op.create_table('notification_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_records_created_at'), 'notification_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_records_ref_id'), 'notification_records', ['ref_id'], unique=False)
    op.create_index(op.f('ix_notification_records_scheduled_at'), 'notification_records', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_notification_records_status'), 'notification_records', ['status'], unique=False)
    op.create_index(op.f('ix_notification_records_type'), 'notification_records', ['type'], unique=False)
    op.create_table('operating_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_expenses_category'), 'operating_expenses', ['category'], unique=False)
    op.create_index(op.f('ix_operating_expenses_deleted_at'), 'operating_expenses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_operating_expenses_occurred_at'), 'operating_expenses', ['occurred_at'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('ix_operation_logs_target_id'), 'operation_logs', ['target_id'], unique=False)
    op.create_table('product_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_cost', sa.Float(), nullable=False),
    sa.Column('default_sale_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_xianyu_account_id', sa.Integer(), nullable=True),
    sa.Column('source_xianyu_item_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_templates_category'), 'product_templates', ['category'], unique=False)
    op.create_index(op.f('ix_product_templates_is_active'), 'product_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_templates_name'), 'product_templates', ['name'], unique=False)
    op.create_index(op.f('ix_product_templates_source_xianyu_account_id'), 'product_templates', ['source_xianyu_account_id'], unique=False)
    op.create_index(op.f('ix_product_templates_source_xianyu_item_id'), 'product_templates', ['source_xianyu_item_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('rebate_rate', sa.Float(), nullable=False),
    sa.Column('rebate_base', sa.String(length=10), nullable=False),
    sa.Column('vip_threshold', sa.Float(), nullable=False),
    sa.Column('core_threshold', sa.Float(), nullable=False),
    sa.Column('vip_trade_count', sa.Integer(), nullable=False),
    sa.Column('core_trade_count', sa.Integer(), nullable=False),
    sa.Column('recall_days', sa.Integer(), nullable=False),
    sa.Column('backup_path', sa.String(length=255), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=255), nullable=False),
    sa.Column('smtp_pass', sa.String(length=512), nullable=False),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xianyu_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('unb', sa.String(length=64), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proxy_config', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xianyu_accounts_status'), 'xianyu_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_xianyu_accounts_unb'), 'xianyu_accounts', ['unb'], unique=False)
    op.create_table('customer_tag_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['customer_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_tag_relations_customer_id'), 'customer_tag_relations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_tag_relations_tag_id'), 'customer_tag_relations', ['tag_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('xianyu_order_no', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_template_id', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('trade_at', sa.DateTime(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warranty_end', sa.DateTime(), nullable=True),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_customer_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_deleted_at'), 'transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_transactions_shipped_at'), 'transactions', ['shipped_at'], unique=False)
    op.create_index(op.f('ix_transactions_source_customer_id'), 'transactions', ['source_customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_trade_at'), 'transactions', ['trade_at'], unique=False)
    op.create_index(op.f('ix_transactions_warranty_end'), 'transactions', ['warranty_end'], unique=False)
    op.create_index(op.f('ix_transactions_xianyu_order_no'), 'transactions', ['xianyu_order_no'], unique=False)
    op.create_table('xianyu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('item_status', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('raw_item', sa.JSON(), nullable=False),
    sa.Column('projected_template_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['xianyu_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'item_id', name='uq_xianyu_items_account_item_id')
    )
    op.create_index(op.f('ix_xianyu_items_account_id'), 'xianyu_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_xianyu_items_item_id'), 'xianyu_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_xianyu_items_item_status'), 'xianyu_items', ['item_status'], unique=False)
    op.create_index(op.f('ix_xianyu_items_last_seen_at'), 'xianyu_items', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_xianyu_items_projected_template_id'), 'xianyu_items', ['projected_template_id'], unique=False)
    op.create_table('xianyu_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('buyer_nick', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('trade_at', sa.DateTime(), nullable=True),
    sa.Column('raw_order', sa.JSON(), nullable=False),
    sa.Column('projected_transaction_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['xianyu_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'order_no', name='uq_xianyu_orders_account_order_no')
    )
    op.create_index(op.f('ix_xianyu_orders_account_id'), 'xianyu_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_xianyu_orders_last_seen_at'), 'xianyu_orders', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_xianyu_orders_order_no'), 'xianyu_orders', ['order_no'], unique=False)
    op.create_index(op.f('ix_xianyu_orders_order_status'), 'xianyu_orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_xianyu_orders_projected_transaction_id'), 'xianyu_orders', ['projected_transaction_id'], unique=False)
    op.create_index(op.f('ix_xianyu_orders_trade_at'), 'xianyu_orders', ['trade_at'], unique=False)
    op.create_table('xianyu_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['xianyu_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xianyu_sync_logs_account_id'), 'xianyu_sync_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_xianyu_sync_logs_created_at'), 'xianyu_sync_logs', ['created_at'], unique=False)
    op.create_table('after_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('issue_desc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('solution_type', sa.String(length=20), nullable=True),
    sa.Column('solution_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('original_transaction_status', sa.String(length=20), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_after_sales_created_at'), 'after_sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_after_sales_deleted_at'), 'after_sales', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_after_sales_status'), 'after_sales', ['status'], unique=False)
    op.create_index(op.f('ix_after_sales_transaction_id'), 'after_sales', ['transaction_id'], unique=False)
    op.create_table('customer_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_links_buyer_id'), 'customer_links', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_customer_links_referrer_id'), 'customer_links', ['referrer_id'], unique=False)
    op.create_table('rebate_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebate_records_created_at'), 'rebate_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_rebate_records_referrer_id'), 'rebate_records', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_rebate_records_status'), 'rebate_records', ['status'], unique=False)
    op.create_index(op.f('ix_rebate_records_transaction_id'), 'rebate_records', ['transaction_id'], unique=False)
    op.create_table('warranty_extensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('old_end', sa.DateTime(), nullable=False),
    sa.Column('new_end', sa.DateTime(), nullable=False),
    sa.Column('extended_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warranty_extensions_transaction_id'), 'warranty_extensions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranty_extensions_transaction_id'), table_name='warranty_extensions')
    op.drop_table('warranty_extensions')
    op.drop_index(op.f('ix_rebate_records_transaction_id'), table_name='rebate_records')
    op.drop_index(op.f('ix_rebate_records_status'), table_name='rebate_records')
    op.drop_index(op.f('ix_rebate_records_referrer_id'), table_name='rebate_records')
    op.drop_index(op.f('ix_rebate_records_created_at'), table_name='rebate_records')
    op.drop_table('rebate_records')
    op.drop_index(op.f('ix_customer_links_referrer_id'), table_name='customer_links')
    op.drop_index(op.f('ix_customer_links_buyer_id'), table_name='customer_links')
    op.drop_table('customer_links')
    op.drop_index(op.f('ix_after_sales_transaction_id'), table_name='after_sales')
    op.drop_index(op.f('ix_after_sales_status'), table_name='after_sales')
    op.drop_index(op.f('ix_after_sales_deleted_at'), table_name='after_sales')
    op.drop_index(op.f('ix_after_sales_created_at'), table_name='after_sales')
    op.drop_table('after_sales')
    op.drop_index(op.f('ix_xianyu_sync_logs_created_at'), table_name='xianyu_sync_logs')
    op.drop_index(op.f('ix_xianyu_sync_logs_account_id'), table_name='xianyu_sync_logs')
    op.drop_table('xianyu_sync_logs')
    op.drop_index(op.f('ix_xianyu_orders_trade_at'), table_name='xianyu_orders')
    op.drop_index(op.f('ix_xianyu_orders_projected_transaction_id'), table_name='xianyu_orders')
    op.drop_index(op.f('ix_xianyu_orders_order_status'), table_name='xianyu_orders')
    op.drop_index(op.f('ix_xianyu_orders_order_no'), table_name='xianyu_orders')
    op.drop_index(op.f('ix_xianyu_orders_last_seen_at'), table_name='xianyu_orders')
    op.drop_index(op.f('ix_xianyu_orders_account_id'), table_name='xianyu_orders')
    op.drop_table('xianyu_orders')
    op.drop_index(op.f('ix_xianyu_items_projected_template_id'), table_name='xianyu_items')
    op.drop_index(op.f('ix_xianyu_items_last_seen_at'), table_name='xianyu_items')
    op.drop_index(op.f('ix_xianyu_items_item_status'), table_name='xianyu_items')
    op.drop_index(op.f('ix_xianyu_items_item_id'), table_name='xianyu_items')
    op.drop_index(op.f('ix_xianyu_items_account_id'), table_name='xianyu_items')
    op.drop_table('xianyu_items')
    op.drop_index(op.f('ix_transactions_xianyu_order_no'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_warranty_end'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_trade_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_shipped_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_deleted_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customer_tag_relations_tag_id'), table_name='customer_tag_relations')
    op.drop_index(op.f('ix_customer_tag_relations_customer_id'), table_name='customer_tag_relations')
    op.drop_table('customer_tag_relations')
    op.drop_index(op.f('ix_xianyu_accounts_unb'), table_name='xianyu_accounts')
    op.drop_index(op.f('ix_xianyu_accounts_status'), table_name='xianyu_accounts')
    op.drop_table('xianyu_accounts')
    op.drop_table('settings')
    op.drop_index(op.f('ix_product_templates_source_xianyu_item_id'), table_name='product_templates')
    op.drop_index(op.f('ix_product_templates_source_xianyu_account_id'), table_name='product_templates')
    op.drop_index(op.f('ix_product_templates_name'), table_name='product_templates')
    op.drop_index(op.f('ix_product_templates_is_active'), table_name='product_templates')
    op.drop_index(op.f('ix_product_templates_category'), table_name='product_templates')
    op.drop_table('product_templates')
    op.drop_index(op.f('ix_operation_logs_target_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_operating_expenses_occurred_at'), table_name='operating_expenses')
    op.drop_index(op.f('ix_operating_expenses_deleted_at'), table_name='operating_expenses')
    op.drop_index(op.f('ix_operating_expenses_category'), table_name='operating_expenses')
    op.drop_table('operating_expenses')
    op.drop_index(op.f('ix_notification_records_type'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_status'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_scheduled_at'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_ref_id'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_created_at'), table_name='notification_records')
    op.drop_table('notification_records')
    op.drop_index(op.f('ix_mail_records_to'), table_name='mail_records')
    op.drop_index(op.f('ix_mail_records_status'), table_name='mail_records')
    op.drop_index(op.f('ix_mail_records_sent_at'), table_name='mail_records')
    op.drop_table('mail_records')
    op.drop_index(op.f('ix_customers_xianyu_nickname'), table_name='customers')
    op.drop_index(op.f('ix_customers_total_spent'), table_name='customers')
    op.drop_index(op.f('ix_customers_level'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_blacklist'), table_name='customers')
    op.drop_index(op.f('ix_customers_deleted_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('customer_tags')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
